services:
  vote:
    build: .
    ports:
      - 8080:8080
    environment:
      - PUBLIC_URL=https://vote-${OKTETO_NAMESPACE}.ramiro.okteto.dev/oauth2/callback
      - OAUTH2_PROXY_URL=$OAUTH2_PROXY_URL

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data
volumes:
  redis: